# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "HelloBlake"

# A description of your site for meta tag, search engine results.
description: "Hello! I'm Blake Watt, Umbraco MVP & Certified Master, Web Developer & Technical Quality Assurance Engineer."

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://helloblake.com"

# Favicon
favicon: images/favicon.png

# Google Analytics
google_analytics: "G-SB3CZEHJ16"

# Site navigation - each item must have a title and a url.
navigation:
  - text: About
    url: /about/
  - text: Community
    url: /community/
  - text: Resume
    url: /resume/
  - text: Archive
    url: /archive/
  - text: Contact
    url: "mailto:hi@helloblake.com"

# The shortname for your Disqus site to enable comments.
disqus: helloblake

# Colors
accent_color: '#B43276'

# Site footer
footer:
  content: ""
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /articles/:title/

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
